apps/website/urls.py
from django.urls import path
from . import views


app_name = "website"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authtools.urls')),
    path('', include('apps.website.urls')),
]

apps/users/models.py
from django.db import models
from authtools.models import AbstractEmailUser


class User(AbstractEmailUser):
    full_name = models.CharField(max_length=255, blank=True, null=True)

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name

    def __str__(self):
        return '<{}>'.format(self.email)

apps/website/models.py
from django.db import models

# Create your models here.

apps/users/views.py
from django.shortcuts import render

# Create your views here.

apps/website/views.py
from django.conf import settings
from django.shortcuts import render
from django.core.mail import EmailMessage
from django.views.generic import TemplateView
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site

from .tasks import send_email_async


def send_email_to_admin(request):
    email_template = "website/email.html"
    current_site = get_current_site(request)

    mail_subject = 'New employee needs activation.'
    message = render_to_string(email_template, {
        'user': request.user,
        'domain': current_site.domain,
    })
    to_email = settings.ADMIN_EMAIL

    send_email_async.delay(mail_subject, message, to_email)


class IndexView(TemplateView):
    template_name = "website/index.html"

    def get(self, request):
        send_email_to_admin(request)
        return super().get(request)

apps/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
</head>
<body data-media-url="{% get_media_prefix %}">
        <div class="row">
                <div class="col-xs-12 col-lg-12">
        <header>
            <nav>
                <ul>
                    <li><a href="{% url "website:index" %}">Home</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Gallery</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url "login" %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="container">
        {% block content %}
        {% endblock %}
        </div>
        <p></p>
        <footer>This is footer</footer>
        </div>
    </div>
</body>
</html>

apps/templates/website/email.html
{% autoescape off %}
Hi admin,
There is a new user with email {{ user.email }} who needs approval and activation.
Please, follow the link to view the user: http://{{ domain }}/admin/users/user/{{ user.pk }}/change/
{% endautoescape %}

apps/templates/website/index.html
{% extends 'shared/base.html' %}
{% block title %}Index page{% endblock %}
{%block content%}
<div>
    {% if user.is_authenticated %}
        <p>Welcome, {{ user.email }}. Thanks for logging in.</p>
    {% else %}
        <p>Welcome, new user. Please log in.</p>
    {% endif %}
</div>
{% endblock %}